mongo:
  image: mongo:3.0.3
zookeeper:
  image: siniida/zookeeper
kafka:
  image: siniida/kafka
  environment:
    - ZOOKEEPERS=zookeeper:2181
  links:
    - zookeeper
nimbus:
  image: siniida/storm
  environment:
    - ROLE=nimbus
    - ZOOKEEPERS=zookeeper:2181
  links:
    - zookeeper
supervisor:
  image: siniida/storm
  environment:
    - ROLE=supervisor
    - ZOOKEEPERS=zookeeper:2181
    - NIMBUS=nimbus
  links:
    - zookeeper
    - nimbus
gungnir:
  image: siniida/gungnir-server
  environment:
    - ROLE=gungnir
    - MODE=distributed
    - MONGO=mongo:27017
    - ZOOKEEPER=zookeeper:2181
    - KAFKA=kafka:9092
    - NIMBUS=nimbus
  links:
    - mongo
    - zookeeper
    - kafka
    - nimbus
    - supervisor
tuplestore:
  image: siniida/gungnir-server
  environment:
    - ROLE=tuple-store
    - MODE=distributed
    - MONGO=mongo:27017
    - ZOOKEEPER=zookeeper:2181
    - KAFKA=kafka:9092
    - NIMBUS=nimbus
  links:
    - mongo
    - zookeeper
    - kafka
    - nimbus
