#!/bin/bash
#
# kafka      kafka server
#
# chkconfig: 35 87 13
# description: kafka server.
# processname: kafka
# config: /opt/kafka/config/server.properties
#

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

RETVAL=0
prog="kafka"
lockfile=/var/lock/subsys/$prog

if [[ $EUID -ne 0 ]] ; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

conf_check() {
    [ -x /opt/kafka/bin/kafka-server-start.sh ] || exit 5
    [ -x /opt/kafka/bin/kafka-server-stop.sh ] || exit 5
    [ -d /opt/kafka/config ] || exit 6
}

start() {
    pid=$(pgrep -f kafka.Kafka)
    if [ ! -z "$pid" ] ; then
        echo "already running as process $pid"
        exit 0
    fi
    conf_check
    # Start daemons.
    echo -n $"Starting kafka: "
    [ -x $CHROOT_UPDATE ] && $CHROOT_UPDATE
    su gennai -c "nohup /opt/kafka/bin/kafkaServer start /opt/kafka/config/server.properties 2>/dev/null 1>&2 &"
    sleep 3
    PS=`ps ax | grep -i 'kafka.Kafka' | grep -v grep | awk '{print $1}'`
    if [ ! -z "$PS" ]; then
        success
        RETVAL=0
    else
        failure $"$prog start"
        RETVAL=1
    fi
    [ $RETVAL -eq 0 ] && touch $lockfile
    echo
    return $RETVAL
}

stop() {
    conf_check
    # Stop daemons.
    echo -n $"Shutting down kafka: "
    su gennai -c "/opt/kafka/bin/kafkaServer stop  2>/dev/null 1>&2" && success || failure $"$prog stop"
    RETVAL=$?
    echo
    return $RETVAL
}

init() {
    conf_check
    pid=$(pgrep -f kafka.Kafka)
    if [ ! -z "$pid" ] ; then
        echo "running as process $pid."
        RETVAL=1
        return
    fi
    LOGDIRS=`grep log.dirs /opt/kafka/config/server.properties | awk -F= '{print $2}'`
    rm -rf ${LOGDIRS}/*
    RETVAL=$?
}

# See how we were called.
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    init)
        init
        ;;
    *)
        echo $"Usage: $0 {start|stop}"
        exit 2
esac

exit $?
