#!/bin/bash
#
# /etc/init.d/tuple-store-server
#
# Startup script for tuple-store-server
#
# chkconfig: 345 91 09
# description: Starts and stops tuple-store-server
. /etc/init.d/functions
gungnirHome=/opt/gungnir-server
serverBin=./bin/tuple-store-server.sh
desc="TupleStoreServer"
outFile=/opt/gungnir-server/tuple-store-server.out
serverUser=gennai
pidFile=/opt/gungnir-server/tuple-store-server.pid

if [[ $EUID -ne 0 ]] ; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

start() {
  if [ -f ${pidFile} ] ; then
    echo "$desc already running as process $pid"
    exit 0
  fi
  echo -n "Starting $desc : "
  cd $gungnirHome
  sudo -u $serverUser $serverBin start >>$outFile 2>&1 && success || failure $"$desc start"
  echo
  sleep 3
  RETVAL=$?

  return $RETVAL
}

stop() {
  echo -n "Shutting down $desc : "
  cd $gungnirHome
  sudo -u $serverUser $serverBin stop >>$outFile 2>&1 && success || failure $"$desc stop"
  RETVAL=$?
  echo

  return $RETVAL
}

restart() {
  stop
  pid=$(/usr/java/default/bin/jps | grep ${desc} | awk '{print $1}')
  until [ -z "${pid}" ]
  do
    pid=$(/usr/java/default/bin/jps | grep ${desc} | awk '{print $1}')
    sleep 1
  done
  start
}

status() {
  pid=`cat ${pidFile}`

  if [ -z $pid ]; then
    echo "${desc} is NOT running."
    RETVAL=1
  else
    echo "${desc} is running (pid is $pid)."
    RETVAL=0
  fi

}

case "$1" in
  start)   start;;
  stop)    stop;;
  restart) restart;;
  status)  status;;
  *)       echo "Usage: $0 {start|stop|restart|status}"
           RETVAL=2;;
esac
exit $RETVAL
